version = 1

test_patterns = ["tests/js/*.js"]

exclude_patterns = ["tests/js/setupTests.js"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs","browser","jest"]
  dependency_file_paths = [
  "codemods/",
  "examples/",
  "src/",
  "tools/"
  ]
  style_guide = "airbnb"

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true