git:
  commitMessage: "chore: release v${version}"
  requireCleanWorkingDir: false
  commit: true

github:
  release: false # This is enabled by default, and I'm not sure we ever want to create a GH release
  autoGenerate: false #This allows github to generate their own version of release notes when creating a release
  #This creates surprisingly good looking release notes on GH releases if we choose to start using them.
  releaseNotes: "npx auto-changelog --stdout --commit-limit false -u --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs"

npm:
  publish: false #Enabled by default. We don't use NPM
  #skipchecks: true #Forcing it skip checks so we don't get an error during the run

hooks:
  after:bump: 'npx auto-changelog -p --output CHANGELOG.md'

#   commitMessage: 'chore: release v${version}'
#   requireCleanWorkingDir: true
# github:
#   release: true
#   autoGenerate: false
#   releaseNotes: 'npx auto-changelog --stdout --commit-limit false -u --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs'
# npm:
#   publish: false
#   skipchecks: true

