git:
  commitMessage: "chore: release v${version}"
  requireCleanWorkingDir: true
github: 
  release: true 
  autoGenerate: false
  releaseNotes: "npx auto-changelog --stdout --commit-limit false -u --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs"
npm:
  publish: false
  skipchecks: true

plugins:

hooks:
  after:bump: "npx auto-changelog -p --output CHANGELOG.md"
