name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches: ['*']

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node_version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install dependencies
        run: yarn 

      - name: Run test
        run: yarn test

      - name: Install c8
        run: yarn global add c8

      - name: Generate Report
        run: c8 report

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 7f2a262dc8f073aca1980984a8faabbef62bae9e4bf72f27fd6864542afaf6b4
        with:
          coverageLocations: ${{github.workspace}}/.coverage/lcov.info:lcov
          verifyDownload: false
          debug: true
                            

