name: ReleaseNotice
on:
  workflow_dispatch:
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To check the github context
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - id: fetch-latest-release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ github.token }}

      - name: Slack Markdown Converter
        id: slack-markdown-body
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        with:
          text: ${{toJSON(steps.fetch-latest-release.outputs.body)}}

      - name: Slack Notification on SUCCESS
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: ":fire::fire: New Release :fire::fire:"
          attachments: |
            [
              {
                "color": "#66D3FF",
                "mrkdown_in": ["fields"],
                "text": "A new version of Continu API version has been released to *Latest*",
                "fields": [
                  {
                    "title": "Version",
                    "value": "<${{ steps.fetch-latest-release.outputs.html_url }}|`${{ steps.fetch-latest-release.outputs.tag_name}}`>",
                    "short": true
                  },
                  {
                    "title": "Site",
                    "value": "<https://learn.continu.co|Learn>",
                    "short": true
                  },
                  {
                    "title": "What's Changed",
                    "value": ${{ steps.slack-markdown-body.outputs.text }}
                  }
                ]
              }
            ]
