name: ReleaseNotice
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To check the github context
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - id: fetch-latest-release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ github.token }}
      - name: Dump release
        run: echo '${{steps.fetch-latest-release.outputs.body}}'
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Hello, Slack!
